services:
  - type: web
    name: barkery
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bakery_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 