# Generated by Django 5.2.1 on 2025-06-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_purchase_delivery_date_purchase_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='delivery_method',
            field=models.CharField(choices=[('manual', 'Manual Pickup'), ('supplier_delivery', 'Supplier Delivery')], default='supplier_delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier_notes',
            field=models.TextField(blank=True, help_text='Notes from supplier or delivery instructions', null=True),
        ),
    ]
